services:
  agent-do:
    image: aiedu-local-agent-do:latest
  workshop:
    image: aiedu-local-workshop:latest
  crawl-api:
    image: aiedu-crawl-api:latest
  crawl-monitor:
    image: aiedu-crawl-monitor:latest
  crawl-worker:
    image: aiedu-crawl-worker:latest
  edurepo-backend:
    image: aiedu-edurepo-backend:latest
